image: "debian:stretch-slim"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
pages:
  script:
  - apt-get update && apt-get -y install python3-minimal python3-wget
  - python3 update_fonts.py
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
